### ISSUE TITLE
Not able to run the interactsh-server 

### ISSUE THREAD

**Issue by raghumannn** [projectdiscovery/interactsh#346] opened 2022-08-02 13:54 UTC
We are trying to setup interactsh-server. But we are hitting this below error. We have already tried to setup this on ubuntu. Since Debian is recommended, we were trying there. But there also we are hitting the same issue. 

```console
-03:/tmp/root# ./interactsh-server -d interactshserver.prancer.cloud

    _       __                       __       __
   (_)___  / /____  _________ ______/ /______/ /_
  / / __ \/ __/ _ \/ ___/ __ '/ ___/ __/ ___/ __ \
 / / / / / /_/  __/ /  / /_/ / /__/ /_(__  ) / / /
/_/_/ /_/\__/\___/_/   \__,_/\___/\__/____/_/ /_/ 1.0.6

                projectdiscovery.io

[INF] Public IP: 137.135.78.15
[INF] Outbound IP: 10.0.0.4
[INF] Requesting SSL Certificate for:  [*.interactshserver.prancer.cloud, interactshserver.prancer.cloud]
[ERR] An error occurred while applying for a certificate, error: [*.interactshserver.prancer.cloud] Obtain: [*.interactshserver.prancer.cloud] solving challenges: waiting for solver certmagic.solverWrapper to be ready: timed out waiting for record to fully propagate; verify DNS provider configuration is correct - last error: <nil> (order=https://acme-v02.api.letsencrypt.org/acme/order/658683696/112438748756) (ca=https://acme-v02.api.letsencrypt.org/directory)
[ERR] Could not generate certs for auto TLS, https will be disabled
[INF] Listening with the following services:
[LDAP] Listening on TCP 10.0.0.4:389
[HTTPS] Listening on TCP 10.0.0.4:443
[DNS] Listening on TCP 10.0.0.4:53
[SMTPS] Listening on TCP 10.0.0.4:587
[DNS] Listening on UDP 10.0.0.4:53
[HTTP] Listening on TCP 10.0.0.4:80
[SMTP] Listening on TCP 10.0.0.4:25
[ERR] Could not serve http on tls: open : no such file or directory
```

**Comment by Mzack9999** [comment] 2022-08-03 08:47
@raghumannn Could you verify that the interactsh DNS server while running is reachable from the outside (even with the certificate error)? 
Considering the output you provided, the following command should be successful:
```console
$ dig interactshserver.prancer.cloud @137.135.78.15
```
I'm seeing a different public IP than the one reported by the output of `interactsh` for this domain. In general, the services must be accessible by the public IP.

**Comment by b1bek** [comment] 2022-08-15 16:10
I am also getting similar error.
![image](https://user-images.githubusercontent.com/43294620/184672331-5aeb5c9d-94e0-4ce4-9823-ea393bbe02f4.png)
Also the dig command output:
`dig bibekshah.com @44.203.251.136  `
![image](https://user-images.githubusercontent.com/43294620/184672458-e4ea5401-e4cb-4d1e-b5dd-799a574d3da7.png)

I am using EC2 with all traffic enabled and namecheap

**Comment by 0xjson** [comment] 2022-09-03 23:02
Hi all,
I also got the similar error, but it seems to work now.

what I did was just manually getting cert from letsencrypt
``` certbot certonly -d <my-domain>```

then added the the custom path for both the ```cert``` and the ```key``` file
```interactsh-server -domain <my-domain> -wildcard -sa -ldap -cert /etc/letsencrypt/live/<my-domain>/fullchain.pem -privkey /etc/letsencrypt/live/<my-domain>/privkey.pem```

![Screenshot 2022-09-04 064427](https://user-images.githubusercontent.com/61111746/188290009-d0881651-108d-4ef6-9301-3099cde4b23c.png)

**Comment by Mzack9999** [comment] 2022-09-28 18:48
@b1bek @raghumannn could you confirm if you were able to get the certificates using directly `certbot`? These issues are hard to investigate as they are mostly related to DNS propagation which, as a consequence, causes the DNS challenge to fail.

**Comment by sudoaza** [comment] 2022-10-10 11:54
Confirm this issue, on a clean ubuntu 20.04. 

Looks like it could be a certmagic issue. It gets dns query but fails to answer properly, 

This shows on debug. Generating the certificate manually with certbot + dns challenge plugin does work. 

```
[DBG] Got acme dns request: 
;; opcode: QUERY, status: NOERROR, id: 21746
;; flags:; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: ; udp: 1232

;; QUESTION SECTION:
;_acme-challenge.xxx.com.	IN	 TXT

handleACMETXTChallenge for zone _acme-challenge.xxx.com. err: no records were found for _acme-challenge.xxx.com.
```

**Comment by Mzack9999** [comment] 2022-12-01 11:04
Closing as not reproducible - The workaround is generally generating certificates with certbot and then just using them in interactsh

**Closed by Mzack9999** 2022-12-01 11:04 UTC
Labels: Priority: Medium, Type: Bug, Investigation

**Comment by dunaevai135** [comment] 2023-01-10 23:56
i had a similar problem.

reason: misconfigured domain
I tried to set up interactsh on a subdomain like the author of the issue and only had A Record
right way (as far as I understand):
```
A  ns1.interactsh.example.com - ip
A  ns2.interactsh.example.com - ip
NS interactsh.example.com - ns1.interactsh.example.com
NS interactsh.example.com - ns2.interactsh.example.com
```
