### ISSUE TITLE
Digitalocean droplets are blocked (?)

### ISSUE THREAD

**Issue by Raywando** [projectdiscovery/interactsh#12] opened 2021-05-02 10:53 UTC
Hi,

It seems like DO droplets are blocked or something. Check out the image. the same issue when I tried a different droplet (different IP).

![WindowsTerminal_76fuVnzfDr](https://user-images.githubusercontent.com/33800255/116810630-84932780-ab4d-11eb-992c-c0012a591434.png)

Also, thank you all for the AMAZING tools you make! <3

**Comment by ehsandeep** [comment] 2021-05-04 13:12
@Raywando you are right, there is something wrong as the domain `interact.sh` is not resolving from DO boxes for unknown reasons, we are now contacting DO support team to know more about this behaviour.

**Comment by mohammedshine** [comment] 2021-05-06 05:49
This is issue can be resolved by adding 46.101.25.250 to the  /etc/hosts file

**Comment by ehsandeep** [comment] 2021-05-06 07:59
@mohammedshine @Raywando We found out the root cause of this issue and fixed in the following PR https://github.com/projectdiscovery/interactsh/pull/21, we have some todos before we restart the server to reflect the fix.

**Closed** 2021-05-06 16:29 UTC
Labels: Status: Completed

**Comment by ehsandeep** [comment] 2021-05-06 16:30
@Raywando this should be resolved now.
